### ISSUE TITLE
add support for vidsrc video streaming api and other same links 

### ISSUE THREAD

**Issue by NeLagina** [benzac-de/msx#4]
example https://vidsrc.to/embed/movie/tt6718170
and https://doc.moplay.org/watch/?v122#NDNUdlBvWUJ2NUJCa2h4cThiN1VNYlVheHZVdVUydjdBa2xRZGRVK1grZm15YTFRK3A0RUtFMFFPbzdNdVZoOHZsZWJraEE9
because it dosen't work in media station links like ended in mp4 work and other media extent
and other links that stream video but not working in media station x

**Comment by benzac-de** [comment]
Thank you for your request.

Your approach is correct, for special video/audio hosting platforms, the video/audio plugin should be used to create a compatible MSX plugin: https://msx.benzac.de/wiki/index.php?title=Video/Audio_Plugin

However, in general, most APIs are too undeveloped to create a proper (full-featured) MSX plugin on your own. So all you can do is asking the hosting operator to create one. For your examples, however, I do not see much hope because the links do not seem very reputable/trustworthy.

**Comment by NeLagina** [comment]
thanks for the answer

**Comment by benzac-de** [comment]
No problem
